{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'A': 1, 'B': 1, 'C': 1, 'D': 1}\n",
      "Vaccum is randomly select to C\n",
      "Moving to Location D...\n",
      "D is dirty\n",
      "Location D has been Cleaned.\n",
      "Moving to Location C...\n",
      "C is dirty\n",
      "Location C has been Cleaned.\n",
      "Moving to Location B...\n",
      "B is dirty\n",
      "Location B has been Cleaned.\n",
      "Moving to Location A...\n",
      "A is dirty\n",
      "Location A has been Cleaned.\n",
      "{'A': 0, 'B': 0, 'C': 0, 'D': 0}\n",
      "Performance Measurement: 0\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "class Eniv(object):\n",
    "    def __init__(self):\n",
    "        self.Rooms={'A':'0','B':'0','C':'0','D':'0'}\n",
    "        self.Rooms['A']=1\n",
    "        self.Rooms['B']=1\n",
    "        self.Rooms['C']=1\n",
    "        self.Rooms['D']=1\n",
    "class Agent(Eniv):\n",
    "    def __init__(self,Eniv):\n",
    "        print(Eniv.Rooms)\n",
    "        Score=0\n",
    "        VaccumLoca = 2\n",
    "        if VaccumLoca == 0:\n",
    "            print(\"Vaccum is randomly select to A\")\n",
    "            if Eniv.Rooms['A'] == 1:\n",
    "                print(\"A is dirty\")\n",
    "                Eniv.Rooms['A']=0\n",
    "                Score=+1\n",
    "                print(\"Location A has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location B...\")\n",
    "                Score -= 1\n",
    "            if Eniv.Rooms['B'] == 1:\n",
    "                print(\"B is dirty\")\n",
    "                Eniv.Rooms['B']=0\n",
    "                Score=+1\n",
    "                print(\"Location B has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location C...\")\n",
    "                Score -= 1\n",
    "            if Eniv.Rooms['C'] == 1:\n",
    "                print(\"C is dirty\")\n",
    "                Eniv.Rooms['C']=0\n",
    "                Score=+1\n",
    "                print(\"Location C has been Cleaned.\")\n",
    "                Score -= 1\n",
    "            if Eniv.Rooms['D'] == 1:\n",
    "                    print(\"D is dirty\")\n",
    "                    Eniv.Rooms['D']=0\n",
    "                    Score=+1\n",
    "                    print(\"Location D has been Cleaned.\")\n",
    "\n",
    "        else:\n",
    "            if VaccumLoca == 1:\n",
    "                print(\"Vaccum is randomly select to B\")\n",
    "                if Eniv.Rooms['A'] == 1:\n",
    "                    print(\"A is dirty\")\n",
    "                    Eniv.Rooms['A']=0\n",
    "                    Score=+1\n",
    "                    print(\"Location A has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Location B...\")\n",
    "                    Score -= 1\n",
    "                if Eniv.Rooms['B'] == 1:\n",
    "                    print(\"B is dirty\")\n",
    "                    Eniv.Rooms['B']=0\n",
    "                    Score=+1\n",
    "                    print(\"Location B has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Location C...\")\n",
    "                    Score -= 1\n",
    "                if Eniv.Rooms['C'] == 1:\n",
    "                    print(\"C is dirty\")\n",
    "                    Eniv.Rooms['C']=0\n",
    "                    Score=+1\n",
    "                    print(\"Location C has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                if Eniv.Rooms['D'] == 1:\n",
    "                    print(\"D is dirty\")\n",
    "                    Eniv.Rooms['D']=0\n",
    "                    Score=+1\n",
    "                    print(\"Location D has been Cleaned.\")\n",
    "                    # move to B\n",
    "            else:\n",
    "                if VaccumLoca == 2:\n",
    "                    print(\"Vaccum is randomly select to C\")\n",
    "                    if Eniv.Rooms['D'] == 1:\n",
    "                        print(\"Moving to Location D...\")\n",
    "                        print(\"D is dirty\")\n",
    "                        Eniv.Rooms['D']=0\n",
    "                        Score=+1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "                        # move to B\n",
    "                        print(\"Moving to Location C...\")\n",
    "                    if Eniv.Rooms['C'] == 1:\n",
    "                        print(\"C is dirty\")\n",
    "                        Eniv.Rooms['C']=0\n",
    "                        Score=+1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                    # move to B\n",
    "                        print(\"Moving to Location B...\")\n",
    "                        Score -= 1\n",
    "                    if Eniv.Rooms['B'] == 1:\n",
    "                        print(\"B is dirty\")\n",
    "                        Eniv.Rooms['B']=0\n",
    "                        Score=+1\n",
    "                        print(\"Location B has been Cleaned.\")\n",
    "                        # move to B\n",
    "                        print(\"Moving to Location A...\")\n",
    "                        Score -= 1\n",
    "                    if Eniv.Rooms['A'] == 1:\n",
    "                        print(\"A is dirty\")\n",
    "                        Eniv.Rooms['A']=0\n",
    "                        Score=+1\n",
    "                        print(\"Location A has been Cleaned.\")\n",
    "                        Score -= 1\n",
    "                    else:\n",
    "                        print(\"Vaccum is randomly select to D\")\n",
    "                        if Eniv.Rooms['D'] == 1:\n",
    "                            print(\"D is dirty\")\n",
    "                            Eniv.Rooms['D']=0\n",
    "                            Score=+1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                            # move to B\n",
    "                            print(\"Moving to Location C...\")\n",
    "                            Score -= 1\n",
    "                        if Eniv.Rooms['C'] == 1:\n",
    "                            print(\"C is dirty\")\n",
    "                            Eniv.Rooms['C']=0\n",
    "                            Score=+1\n",
    "                            print(\"Location C has been Cleaned.\")\n",
    "                            # move to B\n",
    "                            print(\"Moving to Location B...\")\n",
    "                            Score -= 1\n",
    "                        if Eniv.Rooms['B'] == 1:\n",
    "                            print(\"B is dirty\")\n",
    "                            Eniv.Rooms['B']=0\n",
    "                            Score=+1\n",
    "                            print(\"Location B has been Cleaned.\")\n",
    "                            # move to B\n",
    "                            print(\"Moving to Location A...\")\n",
    "                            Score -= 1\n",
    "                        if Eniv.Rooms['A'] == 1:\n",
    "                            print(\"A is dirty\")\n",
    "                            Eniv.Rooms['A']=0\n",
    "                            Score=+1\n",
    "                            print(\"Location A has been Cleaned.\")\n",
    "                            Score -= 1\n",
    "        print (Eniv.Rooms)\n",
    "        print (\"Performance Measurement: \" + str(Score))\n",
    "    \n",
    "theEnvironment = Eniv()\n",
    "theVacuum = Agent(theEnvironment)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
