{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "For Encryption Press '1'\n",
      "For Decryption Press '2'\n",
      "2\n",
      "Enter Cipher Text : bvg\n",
      "\n",
      "Your Plain Text Is : \n",
      "a\n",
      "b\n",
      "c\n"
     ]
    }
   ],
   "source": [
    "choice = input(\"For Encryption Press '1'\\nFor Decryption Press '2'\\n\")\n",
    "if choice == '1':\n",
    "    inputtext = input(\"Enter Plain Text : \") \n",
    "    singleletter  = list(inputtext)\n",
    "    print(\"\\nYour Cipher Text Is : \")\n",
    "    for i in range(len(singleletter )):\n",
    "        if singleletter [i] == 'A' or singleletter [i] == 'a':\n",
    "            print('B')\n",
    "        if singleletter [i] == 'B' or singleletter [i] == 'b':\n",
    "            print('V')\n",
    "        if singleletter [i] == 'C' or singleletter [i] == 'c':\n",
    "            print('G')\n",
    "        if singleletter [i] == 'D' or singleletter [i] == 'd':\n",
    "            print('Q')\n",
    "        if singleletter [i] == 'E' or singleletter [i] == 'e':\n",
    "            print('K')\n",
    "        if singleletter [i] == 'F' or singleletter [i] == 'f':\n",
    "            print('M')\n",
    "        if singleletter [i] == 'G' or singleletter [i] == 'g':\n",
    "            print('N')\n",
    "        if singleletter [i] == 'H' or singleletter [i] == 'h':\n",
    "            print('A')\n",
    "        if singleletter [i] == 'I' or singleletter [i] == 'i':\n",
    "            print('D')\n",
    "        if singleletter [i] == 'J' or singleletter [i] == 'j':\n",
    "            print('Z')\n",
    "        if singleletter [i] == 'K' or singleletter [i] == 'k':\n",
    "            print('C')\n",
    "        if singleletter [i] == 'L' or singleletter [i] == 'l':\n",
    "            print('W')\n",
    "        if singleletter [i] == 'M' or singleletter [i] == 'm':\n",
    "            print('S')\n",
    "        if singleletter [i] == 'N' or singleletter [i] == 'n':\n",
    "            print('E')\n",
    "        if singleletter [i] == 'O' or singleletter [i] == 'o':\n",
    "            print('O')\n",
    "        if singleletter [i] == 'p' or singleletter [i] == 'p':\n",
    "            print('Y')\n",
    "        if singleletter [i] == 'Q' or singleletter [i] == 'q':\n",
    "            print('F')\n",
    "        if singleletter [i] == 'R' or singleletter [i] == 'r':\n",
    "            print('J')\n",
    "        if singleletter [i] == 'S' or singleletter [i] == 's':\n",
    "            print('X')\n",
    "        if singleletter [i] == 'T' or singleletter [i] == 't':\n",
    "            print('H')\n",
    "        if singleletter [i] == 'U' or singleletter [i] == 'u':\n",
    "            print('T')\n",
    "        if singleletter [i] == 'V' or singleletter [i] == 'v':\n",
    "            print('L')\n",
    "        if singleletter [i] == 'W' or singleletter [i] == 'w':\n",
    "            print('P')\n",
    "        if singleletter [i] == 'X' or singleletter [i] == 'x':\n",
    "            print('U')\n",
    "        if singleletter [i] == 'Y' or singleletter [i] == 'y':\n",
    "            print('I')\n",
    "        if singleletter [i] == 'Z' or singleletter [i] == 'z':\n",
    "            print('R')\n",
    "if choice == '2':\n",
    "    inputtext = input(\"Enter Cipher Text : \") \n",
    "    singleletter  = list(inputtext)\n",
    "    print(\"\\nYour Plain Text Is : \")\n",
    "    for i in range(len(singleletter )):\n",
    "        \n",
    "        if singleletter [i] == 'B' or singleletter [i] == 'b':\n",
    "             print('a')\n",
    "        if singleletter [i] == 'V' or singleletter [i] == 'v':\n",
    "            print('b')\n",
    "        if singleletter [i] == 'G' or singleletter [i] == 'g':\n",
    "            print('c')\n",
    "        if singleletter [i] == 'Q' or singleletter [i] == 'q':\n",
    "            print('d')\n",
    "        if singleletter [i] == 'K' or singleletter [i] == 'k':\n",
    "            print('e')\n",
    "        if singleletter [i] == 'M' or singleletter [i] == 'm':\n",
    "            print('f')\n",
    "        if singleletter [i] == 'N' or singleletter [i] == 'n':\n",
    "            print('g')\n",
    "        if singleletter [i] == 'A' or singleletter [i] == 'a':\n",
    "            print('h')\n",
    "        if singleletter [i] == 'D' or singleletter [i] == 'd':\n",
    "            print('i')\n",
    "        if singleletter [i] == 'Z' or singleletter [i] == 'z':\n",
    "            print('j')\n",
    "        if singleletter [i] == 'C' or singleletter [i] == 'c':\n",
    "            print('k')\n",
    "        if singleletter [i] == 'W' or singleletter [i] == 'w':\n",
    "            print('l')\n",
    "        if singleletter [i] == 'S' or singleletter [i] == 's':\n",
    "            print('m')\n",
    "        if singleletter [i] == 'E' or singleletter [i] == 'e':\n",
    "            print('n')\n",
    "        if singleletter [i] == 'O' or singleletter [i] == 'o':\n",
    "            print('o')\n",
    "        if singleletter [i] == 'Y' or singleletter [i] == 'y':\n",
    "            print('p')\n",
    "        if singleletter [i] == 'F' or singleletter [i] == 'f':\n",
    "            print('q')\n",
    "        if singleletter [i] == 'J' or singleletter [i] == 'j':\n",
    "            print('r')\n",
    "        if singleletter [i] == 'X' or singleletter [i] == 'x':\n",
    "            print('s')\n",
    "        if singleletter [i] == 'H' or singleletter [i] == 'h':\n",
    "            print('t')\n",
    "        if singleletter [i] == 'T' or singleletter [i] == 't':\n",
    "            print('u')\n",
    "        if singleletter [i] == 'L' or singleletter [i] == 'l':\n",
    "            print('v')\n",
    "        if singleletter [i] == 'P' or singleletter [i] == 'p':\n",
    "            print('w')\n",
    "        if singleletter [i] == 'U' or singleletter [i] == 'u':\n",
    "            print('x')\n",
    "        if singleletter [i] == 'I' or singleletter [i] == 'i':\n",
    "            print('y')\n",
    "        if singleletter [i] == 'R' or singleletter [i] == 'r':\n",
    "            print('z')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
