{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'A': 0, 'B': 0, 'C': 1}\n",
      "Vaccum is randomly select to C\n",
      "C is dirty\n",
      "Location C has been Cleaned.\n",
      "Moving to Location B...\n",
      "{'A': 0, 'B': 0, 'C': 0}\n",
      "Performance Measurement: 0\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "class Envi(object):\n",
    "    def __init__(self):\n",
    "        self.compartment={'A':'0','B':'0','C':'0'}\n",
    "        self.compartment['A']=0\n",
    "        self.compartment['B']=0\n",
    "        self.compartment['C']=1\n",
    "class Agent(Envi):\n",
    "    def __init__(self,Envi):\n",
    "        print(Envi.compartment)\n",
    "        Score=0\n",
    "        VaccumLoca = random.randint(0,2)\n",
    "        if VaccumLoca == 0:\n",
    "            print(\"Vaccum is randomly select to A\")\n",
    "            if Envi.compartment['A'] == 1:\n",
    "                print(\"A is dirty\")\n",
    "                Envi.compartment['A']=0\n",
    "                Score=+1\n",
    "                print(\"Compartment A has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Compartment B...\")\n",
    "                Score -= 1\n",
    "            if Envi.compartment['B'] == 1:\n",
    "                print(\"B is dirty\")\n",
    "                Envi.compartment['B']=0\n",
    "                Score=+1\n",
    "                print(\"Compartment B has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Compartment C...\")\n",
    "                Score -= 1\n",
    "            if Envi.compartment['C'] == 1:\n",
    "                print(\"C is dirty\")\n",
    "                Envi.compartment['C']=0\n",
    "                Score=+1\n",
    "                print(\"Compartment C has been Cleaned.\")\n",
    "                Score -= 1\n",
    "        else:\n",
    "            if VaccumLoca == 1:\n",
    "                print(\"Vaccum is randomly select to B\")\n",
    "                if Envi.compartment['A'] == 1:\n",
    "                    print(\"A is dirty\")\n",
    "                    Envi.compartment['A']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment A has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Compartment B...\")\n",
    "                    Score -= 1\n",
    "                if Envi.compartment['B'] == 1:\n",
    "                    print(\"B is dirty\")\n",
    "                    Envi.compartment['B']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment B has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Compartment C...\")\n",
    "                    Score -= 1\n",
    "                if Envi.compartment['C'] == 1:\n",
    "                    print(\"C is dirty\")\n",
    "                    Envi.compartment['C']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment C has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "            else:\n",
    "                print(\"Vaccum is randomly select to C\")\n",
    "                if Envi.compartment['C'] == 1:\n",
    "                    print(\"C is dirty\")\n",
    "                    Envi.compartment['C']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment C has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Compartment B...\")\n",
    "                    Score -= 1\n",
    "                if Envi.compartment['B'] == 1:\n",
    "                    print(\"B is dirty\")\n",
    "                    Envi.compartment['B']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment B has been Cleaned.\")\n",
    "                    # move to B\n",
    "                    print(\"Moving to Compartment A...\")\n",
    "                    Score -= 1\n",
    "                if Envi.compartment['A'] == 1:\n",
    "                    print(\"A is dirty\")\n",
    "                    Envi.compartment['A']=0\n",
    "                    Score=+1\n",
    "                    print(\"Compartment A has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "        print (Envi.compartment)\n",
    "        print (\"Performance Measurement: \" + str(Score))\n",
    "    \n",
    "theEnvironment = Envi()\n",
    "theVacuum = Agent(theEnvironment)   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
