{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Vacuum is randomly placed at Location A.\n",
      "Location A is Dirty.\n",
      "Location A has been Cleaned.\n",
      "Moving to Location C...\n",
      "Location D is Dirty.\n",
      "Location D has been Cleaned.\n",
      "Vacuum is randomly placed at Location A.\n",
      "Performance Measurement: 1\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "class Environment(object):\n",
    "    def __init__(self):\n",
    "        self.locationCondition = {'A': '0', 'B': '0','C':'0','D':'0'}\n",
    "        self.locationCondition['A'] = random.randint(0, 1)\n",
    "        self.locationCondition['B'] = random.randint(0, 1)\n",
    "        self.locationCondition['C'] = random.randint(0, 1)\n",
    "        self.locationCondition['D'] = random.randint(0, 1)\n",
    "\n",
    "class SimpleReflexVacuumAgent(Environment):\n",
    "    def __init__(self, Environment):\n",
    "        Score = 0\n",
    "        vacuumLocation = random.randint(0, 3)\n",
    "        if vacuumLocation == 0:\n",
    "            print(\"Vacuum is randomly placed at Location A.\")\n",
    "            # and Location A is Dirty.\n",
    "            if Environment.locationCondition['A'] == 1:\n",
    "                print(\"Location A is Dirty.\")\n",
    "                # suck the dirt  and mark it clean\n",
    "                Environment.locationCondition['A'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location A has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location B...\")\n",
    "                Score -= 1\n",
    "                # if B is Dirty\n",
    "                if Environment.locationCondition['B'] == 1:\n",
    "                    print(\"Location B is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['B'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location B has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                          print(\"Location C is Dirty.\")\n",
    "                          # suck and mark clean\n",
    "                          Environment.locationCondition['C'] = 0;\n",
    "                          Score += 1\n",
    "                          print(\"Location C has been Cleaned.\")\n",
    "                          \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                else: \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                        \n",
    "            elif Environment.locationCondition['B'] == 1:\n",
    "                print(\"Location B is Dirty.\")\n",
    "                # suck and mark clean\n",
    "                Environment.locationCondition['B'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location B has been Cleaned.\")\n",
    "                # move to A\n",
    "                Score -= 1\n",
    "                print(\"Moving to Location A...\")\n",
    "                # if A is Dirty\n",
    "                if Environment.locationCondition['C'] == 1:\n",
    "                    print(\"Location C is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['C'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location C has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "                        Score -= 1\n",
    "                else:\n",
    "                    \n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "        \n",
    "            elif Environment.locationCondition['C'] == 1:\n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                    else:\n",
    "                    \n",
    "                        if Environment.locationCondition['C'] == 1:\n",
    "                            print(\"Location C is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['C'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location C has been Cleaned.\")\n",
    "                    \n",
    "            else:\n",
    "                    \n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")            \n",
    "\n",
    "        elif vacuumLocation == 1:\n",
    "            print(\"Vacuum is randomly placed at Location A.\")\n",
    "            # and Location A is Dirty.\n",
    "            if Environment.locationCondition['B'] == 1:\n",
    "                print(\"Location A is Dirty.\")\n",
    "                # suck the dirt  and mark it clean\n",
    "                Environment.locationCondition['B'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location B has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location A...\")\n",
    "                Score -= 1\n",
    "                # if B is Dirty\n",
    "                if Environment.locationCondition['A'] == 1:\n",
    "                    print(\"Location A is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['A'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location A has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                          print(\"Location C is Dirty.\")\n",
    "                          # suck and mark clean\n",
    "                          Environment.locationCondition['C'] = 0;\n",
    "                          Score += 1\n",
    "                          print(\"Location C has been Cleaned.\")\n",
    "                          \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                else: \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                        \n",
    "            elif Environment.locationCondition['A'] == 1:\n",
    "                print(\"Location A is Dirty.\")\n",
    "                # suck and mark clean\n",
    "                Environment.locationCondition['A'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location A has been Cleaned.\")\n",
    "                # move to A\n",
    "                Score -= 1\n",
    "                print(\"Moving to Location C...\")\n",
    "                # if A is Dirty\n",
    "                if Environment.locationCondition['C'] == 1:\n",
    "                    print(\"Location C is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['C'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location C has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "                        Score -= 1\n",
    "                else:\n",
    "                    \n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "            \n",
    "            elif Environment.locationCondition['C'] == 1:\n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                    else:\n",
    "                    \n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                    \n",
    "            \n",
    "            else:\n",
    "                # move to A\n",
    "                print(\"Moving to Location D...\")\n",
    "              \n",
    "                # if A is Dirty\n",
    "                if Environment.locationCondition['D'] == 1:\n",
    "                    Score -= 1\n",
    "                    print(\"Location D is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['D'] = 0;\n",
    "                    Score += 1\n",
    "                    print (\"Location D has been Cleaned.\")\n",
    "            \n",
    "        \n",
    "        if vacuumLocation == 2:\n",
    "            print(\"Vacuum is randomly placed at Location C.\")\n",
    "            # and Location A is Dirty.\n",
    "            if Environment.locationCondition['C'] == 1:\n",
    "                print(\"Location c is Dirty.\")\n",
    "                # suck the dirt  and mark it clean\n",
    "                Environment.locationCondition['C'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location C has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location A...\")\n",
    "                Score -= 1\n",
    "                # if B is Dirty\n",
    "                if Environment.locationCondition['A'] == 1:\n",
    "                    print(\"Location A is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['A'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location A has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    \n",
    "                    if Environment.locationCondition['B'] == 1:\n",
    "                          print(\"Location B is Dirty.\")\n",
    "                          # suck and mark clean\n",
    "                          Environment.locationCondition['B'] = 0;\n",
    "                          Score += 1\n",
    "                          print(\"Location B has been Cleaned.\")\n",
    "                          \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                          if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                else: \n",
    "                    if Environment.locationCondition['B'] == 1:\n",
    "                        print(\"Location B is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['B'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location B has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                              print(\"Location D is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['D'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location D has been Cleaned.\")\n",
    "                    else: \n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                        \n",
    "            elif Environment.locationCondition['A'] == 1:\n",
    "                print(\"Location A is Dirty.\")\n",
    "                # suck and mark clean\n",
    "                Environment.locationCondition['A'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location A has been Cleaned.\")\n",
    "                # move to A\n",
    "                Score -= 1\n",
    "                print(\"Moving to Location B...\")\n",
    "                # if A is Dirty\n",
    "                if Environment.locationCondition['B'] == 1:\n",
    "                    print(\"Location B is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['B'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location B has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "                        Score -= 1\n",
    "                else:\n",
    "                    \n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\")\n",
    "            \n",
    "            elif Environment.locationCondition['B'] == 1:\n",
    "                    if Environment.locationCondition['B'] == 1:\n",
    "                        print(\"Location B is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['B'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location B has been Cleaned.\")\n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                    else:\n",
    "                    \n",
    "                        if Environment.locationCondition['D'] == 1:\n",
    "                            print(\"Location D is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['D'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location D has been Cleaned.\")\n",
    "                    \n",
    "            else:\n",
    "                    \n",
    "                    if Environment.locationCondition['D'] == 1:\n",
    "                        print(\"Location D is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['D'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location D has been Cleaned.\") \n",
    "                        \n",
    "        else:\n",
    "            print(\"Vacuum is randomly placed at Location A.\")\n",
    "            # and Location A is Dirty.\n",
    "            if Environment.locationCondition['D'] == 1:\n",
    "                print(\"Location D is Dirty.\")\n",
    "                # suck the dirt  and mark it clean\n",
    "                Environment.locationCondition['D'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location D has been Cleaned.\")\n",
    "                # move to B\n",
    "                print(\"Moving to Location B...\")\n",
    "                Score -= 1\n",
    "                # if B is Dirty\n",
    "                if Environment.locationCondition['B'] == 1:\n",
    "                    print(\"Location B is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['B'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location B has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                          print(\"Location C is Dirty.\")\n",
    "                          # suck and mark clean\n",
    "                          Environment.locationCondition['C'] = 0;\n",
    "                          Score += 1\n",
    "                          print(\"Location C has been Cleaned.\")\n",
    "                          \n",
    "                          if Environment.locationCondition['A'] == 1:\n",
    "                              print(\"Location A is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['A'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location A has been Cleaned.\")\n",
    "                    else: \n",
    "                          if Environment.locationCondition['A'] == 1:\n",
    "                              print(\"Location A is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['A'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location A has been Cleaned.\")\n",
    "                else: \n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['A'] == 1:\n",
    "                              print(\"Location A is Dirty.\")\n",
    "                              # suck and mark clean\n",
    "                              Environment.locationCondition['A'] = 0;\n",
    "                              Score += 1\n",
    "                              print(\"Location A has been Cleaned.\")\n",
    "                    else: \n",
    "                        if Environment.locationCondition['A'] == 1:\n",
    "                            print(\"Location A is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['A'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location A has been Cleaned.\")\n",
    "                        \n",
    "            elif Environment.locationCondition['B'] == 1:\n",
    "                print(\"Location B is Dirty.\")\n",
    "                # suck and mark clean\n",
    "                Environment.locationCondition['B'] = 0;\n",
    "                Score += 1\n",
    "                print(\"Location B has been Cleaned.\")\n",
    "                # move to A\n",
    "                Score -= 1\n",
    "                print(\"Moving to Location C...\")\n",
    "                # if A is Dirty\n",
    "                if Environment.locationCondition['C'] == 1:\n",
    "                    print(\"Location C is Dirty.\")\n",
    "                    # suck and mark clean\n",
    "                    Environment.locationCondition['C'] = 0;\n",
    "                    Score += 1\n",
    "                    print(\"Location C has been Cleaned.\")\n",
    "                    Score -= 1\n",
    "                    if Environment.locationCondition['A'] == 1:\n",
    "                        print(\"Location A is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['A'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location A has been Cleaned.\")\n",
    "                        Score -= 1\n",
    "                else:\n",
    "                    \n",
    "                    if Environment.locationCondition['A'] == 1:\n",
    "                        print(\"Location A is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['A'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location A has been Cleaned.\")\n",
    "        \n",
    "            elif Environment.locationCondition['C'] == 1:\n",
    "                    if Environment.locationCondition['C'] == 1:\n",
    "                        print(\"Location C is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['C'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location C has been Cleaned.\")\n",
    "                        if Environment.locationCondition['A'] == 1:\n",
    "                            print(\"Location A is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['A'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location A has been Cleaned.\")\n",
    "                    else:\n",
    "                    \n",
    "                        if Environment.locationCondition['C'] == 1:\n",
    "                            print(\"Location C is Dirty.\")\n",
    "                            # suck and mark clean\n",
    "                            Environment.locationCondition['C'] = 0;\n",
    "                            Score += 1\n",
    "                            print(\"Location C has been Cleaned.\")\n",
    "                    \n",
    "            else:\n",
    "                    \n",
    "                    if Environment.locationCondition['A'] == 1:\n",
    "                        print(\"Location A is Dirty.\")\n",
    "                        # suck and mark clean\n",
    "                        Environment.locationCondition['A'] = 0;\n",
    "                        Score += 1\n",
    "                        print(\"Location A has been Cleaned.\")                    \n",
    "        # done cleaning\n",
    "        print (\"Performance Measurement: \" + str(Score))\n",
    "\n",
    "\n",
    "theEnvironment = Environment()\n",
    "theVacuum = SimpleReflexVacuumAgent(theEnvironment)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
